/**
 * 【課程規劃報告產生器 - 配色集】
 */
import type { Palette } from "../../types/template";

export const PALETTES: Palette[] = [
  {
    id: "navy-white",
    name: "中華電信深藍",
    primary: "#1f3a8a",
    primaryFg: "#ffffff",
    accent: "#3b82f6",
    ink: "#22263a",
    paper: "#ffffff",
    border: "#cbd5e1",
    sectionBg: "#eef2ff",
    tableHeaderBg: "#1f3a8a",
    tableHeaderFg: "#ffffff",
    tableBorder: "#94a3b8",
  },
  {
    id: "emerald-fresh",
    name: "翠綠清新",
    primary: "#047857",
    primaryFg: "#ffffff",
    accent: "#10b981",
    ink: "#1f2937",
    paper: "#ffffff",
    border: "#d1d5db",
    sectionBg: "#ecfdf5",
    tableHeaderBg: "#047857",
    tableHeaderFg: "#ffffff",
    tableBorder: "#9ca3af",
  },
  {
    id: "warm-amber",
    name: "暖陽琥珀",
    primary: "#b45309",
    primaryFg: "#ffffff",
    accent: "#f59e0b",
    ink: "#27241a",
    paper: "#fffbeb",
    border: "#e5e0c8",
    sectionBg: "#fef3c7",
    tableHeaderBg: "#b45309",
    tableHeaderFg: "#ffffff",
    tableBorder: "#a8a29e",
  },
  {
    id: "vibrant-magenta",
    name: "活力洋紅",
    primary: "#9d174d",
    primaryFg: "#ffffff",
    accent: "#ec4899",
    ink: "#27121f",
    paper: "#ffffff",
    border: "#e2c5d3",
    sectionBg: "#fce7f3",
    tableHeaderBg: "#9d174d",
    tableHeaderFg: "#ffffff",
    tableBorder: "#a3a3a3",
  },
  {
    id: "minimal-mono",
    name: "極簡黑白",
    primary: "#111827",
    primaryFg: "#ffffff",
    accent: "#374151",
    ink: "#111827",
    paper: "#ffffff",
    border: "#d4d4d8",
    sectionBg: "#f4f4f5",
    tableHeaderBg: "#111827",
    tableHeaderFg: "#ffffff",
    tableBorder: "#a1a1aa",
  },
  {
    id: "ocean-cyan",
    name: "海洋青藍",
    primary: "#0e7490",
    primaryFg: "#ffffff",
    accent: "#06b6d4",
    ink: "#0f172a",
    paper: "#f0fdff",
    border: "#bae6fd",
    sectionBg: "#cffafe",
    tableHeaderBg: "#0e7490",
    tableHeaderFg: "#ffffff",
    tableBorder: "#94a3b8",
  },
];

export function getPalette(id: string | undefined | null): Palette {
  return PALETTES.find((p) => p.id === id) ?? PALETTES[0];
}
