import type { Palette } from '@edm/types/theme';

export const PALETTE_PRESETS: Palette[] = [
  {
    id: 'cht-brand',
    name: '中華電信品牌藍',
    description: '中華電信識別色，沉穩可信',
    tokens: {
      primary: '#0070C0',
      secondary: '#003D6B',
      accent: '#F5A623',
      bg: '#FFFFFF',
      surface: '#F4F7FB',
      textPrimary: '#0F1B2D',
      textSecondary: '#4A5C75',
      border: '#D8E3EE',
    },
  },
  {
    id: 'navy-gold',
    name: '沉穩深藍金',
    description: '商務正式、高質感',
    tokens: {
      primary: '#1A2A4A',
      secondary: '#0D162B',
      accent: '#C8A96A',
      bg: '#FFFFFF',
      surface: '#F6F4EE',
      textPrimary: '#0D162B',
      textSecondary: '#4F5A75',
      border: '#E2DCCB',
    },
  },
  {
    id: 'tech-neon',
    name: '科技霓虹紫',
    description: '前沿科技、Vibe Coding 等技術課首選',
    tokens: {
      primary: '#7C3AED',
      secondary: '#1E1B4B',
      accent: '#22D3EE',
      bg: '#0F0B1F',
      surface: '#1B1538',
      textPrimary: '#F4F0FF',
      textSecondary: '#B8AED9',
      border: '#3A2F66',
    },
  },
  {
    id: 'forest',
    name: '自然森綠',
    description: '永續、ESG 課程適用',
    tokens: {
      primary: '#2F855A',
      secondary: '#1C4532',
      accent: '#D69E2E',
      bg: '#FFFFFF',
      surface: '#F0F7F2',
      textPrimary: '#1A2E22',
      textSecondary: '#476254',
      border: '#D7E5DD',
    },
  },
  {
    id: 'sunrise',
    name: '暖陽橙',
    description: '熱情活力、適合行銷與創新主題',
    tokens: {
      primary: '#EA580C',
      secondary: '#9A3412',
      accent: '#FACC15',
      bg: '#FFFBF5',
      surface: '#FEF3E7',
      textPrimary: '#3D1F0B',
      textSecondary: '#6B4A30',
      border: '#F4D9BB',
    },
  },
  {
    id: 'academic-indigo',
    name: '學術藏青',
    description: '正式、權威，最像現有公文 EDM',
    tokens: {
      primary: '#312E81',
      secondary: '#1E1B4B',
      accent: '#DC2626',
      bg: '#FFFFFF',
      surface: '#F4F4F8',
      textPrimary: '#1E1B4B',
      textSecondary: '#52527A',
      border: '#DDD6FE',
    },
  },
  {
    id: 'morandi',
    name: '莫蘭迪',
    description: '低飽和度、高級感',
    tokens: {
      primary: '#8C7B6B',
      secondary: '#6B5D52',
      accent: '#A4B1A0',
      bg: '#F5F1EC',
      surface: '#EAE3DB',
      textPrimary: '#3A312A',
      textSecondary: '#6B5E54',
      border: '#D9D0C5',
    },
  },
  {
    id: 'mono',
    name: '黑白極簡',
    description: '極簡優雅、襯托內容',
    tokens: {
      primary: '#0A0A0A',
      secondary: '#262626',
      accent: '#DC2626',
      bg: '#FFFFFF',
      surface: '#FAFAFA',
      textPrimary: '#0A0A0A',
      textSecondary: '#525252',
      border: '#E5E5E5',
    },
  },
  // v0.6.0：極光霧青 —— 青綠主色 + 粉紫強調，搭配 gradient / 永續 / 創新主題
  {
    id: 'aurora',
    name: '極光霧青',
    description: '青綠 + 粉紫，永續 / ESG / 創新主題',
    tokens: {
      primary: '#0E7C7B',
      secondary: '#0B4F50',
      accent: '#C95E9E',
      bg: '#F4FBFA',
      surface: '#E5F3F2',
      textPrimary: '#0B2D2D',
      textSecondary: '#3F5F5F',
      border: '#C5DFDD',
    },
  },
  // v0.6.0：烏黑朱紅 —— 極深灰底 + 朱紅，搭配 editorial / 高階主管 / 領導力
  {
    id: 'ember',
    name: '烏黑朱紅',
    description: '極深灰 + 朱紅，編輯 / 高階主管 / 領導力',
    tokens: {
      primary: '#B00020',
      secondary: '#1A1A1A',
      accent: '#E5C089',
      bg: '#FAF7F3',
      surface: '#F0EBE3',
      textPrimary: '#0F0F0F',
      textSecondary: '#4A4A4A',
      border: '#D9D2C5',
    },
  },
];

export const getPaletteById = (id: string): Palette =>
  PALETTE_PRESETS.find((p) => p.id === id) ?? PALETTE_PRESETS[0];
